### ISSUE TITLE
Performnace concern as each request starts a new NestJS application

### ISSUE THREAD

**Issue by anthopark** [robertIsaac/NestJS-with-Firebase#9]
Hello, I'm very new to NestJS and thanks to your very detailed article and the source code here, I was able to start building my upcoming project with Firebase. 

I just had one concern (that might not be valid as I'm a beginner!): as the app scales, I'm afraid it will take longer to start the application. This may result in a longer response time as the codebase gets larger. Is this a valid concern? Also, is there a way for the Firebase functions to stay running and have the NestJS app listen to requests for an indefinite amount of time?

**Comment by robertIsaac** [comment]
> Hello, I'm very new to NestJS and thanks to your very detailed article and the source code here, I was able to start building my upcoming project with Firebase.
> 
> I just had one concern (that might not be valid as I'm a beginner!): as the app scales, I'm afraid it will take longer to start the application. This may result in a longer response time as the codebase gets larger. Is this a valid concern? Also, is there a way for the Firebase functions to stay running and have the NestJS app listen to requests for an indefinite amount of time?

This is a valid point
My recommendation would be that if your application grow to use docker and Kubernetes
